### PR TITLE
Adding a way to allow insecure https connections.

### PR DESCRIPTION
**Pull request by jbristow**
I was using this to test http-kit, and I noticed that when sending things to self-signed certs I needed a way to flip the `insecure?` option.

If you could give me a rough idea of how you'd like this tested I'll add it in.

### CODE REVIEW

**Comment by sgerrand** [comment]
@jbristow: Apologies for the massively belated response. Would you please expand on the reasons for needing to use this with a self-signed SSL certificate? With the advent of HTTP2 and free SSL certificate providers like Let's Encrypt, we'd prefer not to add this feature in.

**Comment by sgerrand** [comment]
If you are still keen to add it in, I'd suggest adding integration tests against both a "real" HTTPS URL (e.g. https://www.google.com) and a self-signed variety.

**Comment by jbristow** [comment]
Heh, when I did this, I was working in an environment where there were a number of self-signed certs on internal systems.

Additionally, I think I was working on a PR for http-kit, and needed a quick proxy, so I hacked on this one until it worked.  Feel free to close since I don't have time to work on this at the moment.

**Comment by sgerrand** [comment]
🙇

**Pull request closed without merging**
